version: '3.3'
services:
  fe-proxy:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: fe-proxy
    volumes:
      - .:/usr/src/app
    ports:
      - 8888:6969
    environment:
      - CHOKIDAR_USEPOLLING=true
